VERSION="2.2.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GDXDFUJGC7ZDNTFKZUORDSNXM3GFUSYJMFPLYP32P3Z46PG3NGEHYPLX"]

[DOCUMENTATION]
ORG_NAME="User Xperience Lab Model"
ORG_URL="https://uxlm.github.io/"
ORG_LOGO ="https://uxlm.github.io/images/internet.gif"
ORG_DESCRIPTION="The User Xperience Lab Model (often referred to as UX Lab Model) is typically a framework used in the field of user experience (UX) design and research. While there isn't a universally accepted definition of this specific term, the concept generally revolves around creating an environment where designers, researchers, and stakeholders can collaborate to understand user needs, behaviors, and preferences."

[[CURRENCIES]]
code="GUI"
name="graphical user interface"
issuer="GDXDFUJGC7ZDNTFKZUORDSNXM3GFUSYJMFPLYP32P3Z46PG3NGEHYPLX"
desc="A graphical user interface, or GUI, is a form of user interface that allows users to interact with electronic devices through graphical icons and visual indicators such as secondary notation. In many applications, GUIs are used instead of text-based UIs, which are based on typed command labels or text navigation."
image="https://uxlm.github.io/images/gui.png"
conditions="Better alignment of products with user needs, resulting in higher conversion rates and lower churn."
fixed_number=100000000000
is_asset_anchored=false
display_decimals=7

[[CURRENCIES]]
code="CLI"
name="command line interface"
issuer="GDXDFUJGC7ZDNTFKZUORDSNXM3GFUSYJMFPLYP32P3Z46PG3NGEHYPLX"
desc="A command line interface (CLI) is a software mechanism you use to interact with your operating system using your keyboard."
image="https://uxlm.github.io/images/cli.png"
conditions="Improved user satisfaction and engagement through better-designed products."
fixed_number=100000000000
is_asset_anchored=false
display_decimals=7
