VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[""]

[DOCUMENTATION]
ORG_NAME=""
ORG_URL=""
ORG_LOGO =""
ORG_OFFICIAL_EMAIL=""
ORG_SUPPORT_EMAIL=""
ORG_DESCRIPTION=""

[[CURRENCIES]]
code=""
name=""
issuer=""
is_asset_anchored=false
display_decimals=7
desc=""
image=""
conditions=""
fixed_number=1000000000
